/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mycompany.myapp.dao;

import com.mycompany.myapp.dto.*;
import com.mycompany.myapp.exceptions.*;

public interface LivrosDao
{
	/** 
	 * Inserts a new row in the livros table.
	 */
	public LivrosPk insert(Livros dto) throws LivrosDaoException;

	/** 
	 * Updates a single row in the livros table.
	 */
	public void update(LivrosPk pk, Livros dto) throws LivrosDaoException;

	/** 
	 * Deletes a single row in the livros table.
	 */
	public void delete(LivrosPk pk) throws LivrosDaoException;

	/** 
	 * Returns the rows from the livros table that matches the specified primary-key value.
	 */
	public Livros findByPrimaryKey(LivrosPk pk) throws LivrosDaoException;

	/** 
	 * Returns all rows from the livros table that match the criteria 'Livro = :livro'.
	 */
	public Livros findByPrimaryKey(int livro) throws LivrosDaoException;

	/** 
	 * Returns all rows from the livros table that match the criteria ''.
	 */
	public Livros[] findAll() throws LivrosDaoException;

	/** 
	 * Returns all rows from the livros table that match the criteria 'Livro = :livro'.
	 */
	public Livros[] findWhereLivroEquals(int livro) throws LivrosDaoException;

	/** 
	 * Returns all rows from the livros table that match the criteria 'Editorial = :editorial'.
	 */
	public Livros[] findWhereEditorialEquals(String editorial) throws LivrosDaoException;

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows);

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows();

	/** 
	 * Returns all rows from the livros table that match the specified arbitrary SQL statement
	 */
	public Livros[] findByDynamicSelect(String sql, Object[] sqlParams) throws LivrosDaoException;

	/** 
	 * Returns all rows from the livros table that match the specified arbitrary SQL statement
	 */
	public Livros[] findByDynamicWhere(String sql, Object[] sqlParams) throws LivrosDaoException;

}
