/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mycompany.myapp.dto;

import com.mycompany.myapp.dao.*;
import com.mycompany.myapp.factory.*;
import com.mycompany.myapp.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class DiscLivro implements Serializable
{
	/** 
	 * This attribute maps to the column idDisciplina in the disc_livro table.
	 */
	protected int idDisciplina;

	/** 
	 * This attribute maps to the column Livro in the disc_livro table.
	 */
	protected String livro;

	/**
	 * Method 'DiscLivro'
	 * 
	 */
	public DiscLivro()
	{
	}

	/**
	 * Method 'getIdDisciplina'
	 * 
	 * @return int
	 */
	public int getIdDisciplina()
	{
		return idDisciplina;
	}

	/**
	 * Method 'setIdDisciplina'
	 * 
	 * @param idDisciplina
	 */
	public void setIdDisciplina(int idDisciplina)
	{
		this.idDisciplina = idDisciplina;
	}

	/**
	 * Method 'getLivro'
	 * 
	 * @return String
	 */
	public String getLivro()
	{
		return livro;
	}

	/**
	 * Method 'setLivro'
	 * 
	 * @param livro
	 */
	public void setLivro(String livro)
	{
		this.livro = livro;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof DiscLivro)) {
			return false;
		}
		
		final DiscLivro _cast = (DiscLivro) _other;
		if (idDisciplina != _cast.idDisciplina) {
			return false;
		}
		
		if (livro == null ? _cast.livro != livro : !livro.equals( _cast.livro )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idDisciplina;
		if (livro != null) {
			_hashCode = 29 * _hashCode + livro.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return DiscLivroPk
	 */
	public DiscLivroPk createPk()
	{
		return new DiscLivroPk(idDisciplina);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mycompany.myapp.dto.DiscLivro: " );
		ret.append( "idDisciplina=" + idDisciplina );
		ret.append( ", livro=" + livro );
		return ret.toString();
	}

}
