/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mycompany.myapp.dto;

import com.mycompany.myapp.dao.*;
import com.mycompany.myapp.factory.*;
import com.mycompany.myapp.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Disciplinas implements Serializable
{
	/** 
	 * This attribute maps to the column idDisciplina in the disciplinas table.
	 */
	protected int idDisciplina;

	/** 
	 * This attribute maps to the column Disciplina in the disciplinas table.
	 */
	protected String disciplina;

	/**
	 * Method 'Disciplinas'
	 * 
	 */
	public Disciplinas()
	{
	}

	/**
	 * Method 'getIdDisciplina'
	 * 
	 * @return int
	 */
	public int getIdDisciplina()
	{
		return idDisciplina;
	}

	/**
	 * Method 'setIdDisciplina'
	 * 
	 * @param idDisciplina
	 */
	public void setIdDisciplina(int idDisciplina)
	{
		this.idDisciplina = idDisciplina;
	}

	/**
	 * Method 'getDisciplina'
	 * 
	 * @return String
	 */
	public String getDisciplina()
	{
		return disciplina;
	}

	/**
	 * Method 'setDisciplina'
	 * 
	 * @param disciplina
	 */
	public void setDisciplina(String disciplina)
	{
		this.disciplina = disciplina;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Disciplinas)) {
			return false;
		}
		
		final Disciplinas _cast = (Disciplinas) _other;
		if (idDisciplina != _cast.idDisciplina) {
			return false;
		}
		
		if (disciplina == null ? _cast.disciplina != disciplina : !disciplina.equals( _cast.disciplina )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idDisciplina;
		if (disciplina != null) {
			_hashCode = 29 * _hashCode + disciplina.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return DisciplinasPk
	 */
	public DisciplinasPk createPk()
	{
		return new DisciplinasPk(idDisciplina);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mycompany.myapp.dto.Disciplinas: " );
		ret.append( "idDisciplina=" + idDisciplina );
		ret.append( ", disciplina=" + disciplina );
		return ret.toString();
	}

}
