/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mycompany.myapp.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the livros table.
 */
public class LivrosPk implements Serializable
{
	protected int livro;

	/** 
	 * This attribute represents whether the primitive attribute livro is null.
	 */
	protected boolean livroNull;

	/** 
	 * Sets the value of livro
	 */
	public void setLivro(int livro)
	{
		this.livro = livro;
	}

	/** 
	 * Gets the value of livro
	 */
	public int getLivro()
	{
		return livro;
	}

	/**
	 * Method 'LivrosPk'
	 * 
	 */
	public LivrosPk()
	{
	}

	/**
	 * Method 'LivrosPk'
	 * 
	 * @param livro
	 */
	public LivrosPk(final int livro)
	{
		this.livro = livro;
	}

	/** 
	 * Sets the value of livroNull
	 */
	public void setLivroNull(boolean livroNull)
	{
		this.livroNull = livroNull;
	}

	/** 
	 * Gets the value of livroNull
	 */
	public boolean isLivroNull()
	{
		return livroNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof LivrosPk)) {
			return false;
		}
		
		final LivrosPk _cast = (LivrosPk) _other;
		if (livro != _cast.livro) {
			return false;
		}
		
		if (livroNull != _cast.livroNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + livro;
		_hashCode = 29 * _hashCode + (livroNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mycompany.myapp.dto.LivrosPk: " );
		ret.append( "livro=" + livro );
		return ret.toString();
	}

}
