/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mycompany.myapp.dto;

import com.mycompany.myapp.dao.*;
import com.mycompany.myapp.factory.*;
import com.mycompany.myapp.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Livros implements Serializable
{
	/** 
	 * This attribute maps to the column Livro in the livros table.
	 */
	protected int livro;

	/** 
	 * This attribute maps to the column Editorial in the livros table.
	 */
	protected String editorial;

	/**
	 * Method 'Livros'
	 * 
	 */
	public Livros()
	{
	}

	/**
	 * Method 'getLivro'
	 * 
	 * @return int
	 */
	public int getLivro()
	{
		return livro;
	}

	/**
	 * Method 'setLivro'
	 * 
	 * @param livro
	 */
	public void setLivro(int livro)
	{
		this.livro = livro;
	}

	/**
	 * Method 'getEditorial'
	 * 
	 * @return String
	 */
	public String getEditorial()
	{
		return editorial;
	}

	/**
	 * Method 'setEditorial'
	 * 
	 * @param editorial
	 */
	public void setEditorial(String editorial)
	{
		this.editorial = editorial;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Livros)) {
			return false;
		}
		
		final Livros _cast = (Livros) _other;
		if (livro != _cast.livro) {
			return false;
		}
		
		if (editorial == null ? _cast.editorial != editorial : !editorial.equals( _cast.editorial )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + livro;
		if (editorial != null) {
			_hashCode = 29 * _hashCode + editorial.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return LivrosPk
	 */
	public LivrosPk createPk()
	{
		return new LivrosPk(livro);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mycompany.myapp.dto.Livros: " );
		ret.append( "livro=" + livro );
		ret.append( ", editorial=" + editorial );
		return ret.toString();
	}

}
