/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mycompany.myapp.dto;

import com.mycompany.myapp.dao.*;
import com.mycompany.myapp.factory.*;
import com.mycompany.myapp.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Professor implements Serializable
{
	/** 
	 * This attribute maps to the column idProfessor in the professor table.
	 */
	protected int idProfessor;

	/** 
	 * This attribute maps to the column Professor in the professor table.
	 */
	protected String professor;

	/**
	 * Method 'Professor'
	 * 
	 */
	public Professor()
	{
	}

	/**
	 * Method 'getIdProfessor'
	 * 
	 * @return int
	 */
	public int getIdProfessor()
	{
		return idProfessor;
	}

	/**
	 * Method 'setIdProfessor'
	 * 
	 * @param idProfessor
	 */
	public void setIdProfessor(int idProfessor)
	{
		this.idProfessor = idProfessor;
	}

	/**
	 * Method 'getProfessor'
	 * 
	 * @return String
	 */
	public String getProfessor()
	{
		return professor;
	}

	/**
	 * Method 'setProfessor'
	 * 
	 * @param professor
	 */
	public void setProfessor(String professor)
	{
		this.professor = professor;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Professor)) {
			return false;
		}
		
		final Professor _cast = (Professor) _other;
		if (idProfessor != _cast.idProfessor) {
			return false;
		}
		
		if (professor == null ? _cast.professor != professor : !professor.equals( _cast.professor )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idProfessor;
		if (professor != null) {
			_hashCode = 29 * _hashCode + professor.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ProfessorPk
	 */
	public ProfessorPk createPk()
	{
		return new ProfessorPk(idProfessor);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mycompany.myapp.dto.Professor: " );
		ret.append( "idProfessor=" + idProfessor );
		ret.append( ", professor=" + professor );
		return ret.toString();
	}

}
