/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mycompany.myapp.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the prof_disc table.
 */
public class ProfDiscPk implements Serializable
{
	protected int idProfessor;

	protected String idDisciplina;

	/** 
	 * This attribute represents whether the primitive attribute idProfessor is null.
	 */
	protected boolean idProfessorNull;

	/** 
	 * Sets the value of idProfessor
	 */
	public void setIdProfessor(int idProfessor)
	{
		this.idProfessor = idProfessor;
	}

	/** 
	 * Gets the value of idProfessor
	 */
	public int getIdProfessor()
	{
		return idProfessor;
	}

	/** 
	 * Sets the value of idDisciplina
	 */
	public void setIdDisciplina(String idDisciplina)
	{
		this.idDisciplina = idDisciplina;
	}

	/** 
	 * Gets the value of idDisciplina
	 */
	public String getIdDisciplina()
	{
		return idDisciplina;
	}

	/**
	 * Method 'ProfDiscPk'
	 * 
	 */
	public ProfDiscPk()
	{
	}

	/**
	 * Method 'ProfDiscPk'
	 * 
	 * @param idProfessor
	 * @param idDisciplina
	 */
	public ProfDiscPk(final int idProfessor, final String idDisciplina)
	{
		this.idProfessor = idProfessor;
		this.idDisciplina = idDisciplina;
	}

	/** 
	 * Sets the value of idProfessorNull
	 */
	public void setIdProfessorNull(boolean idProfessorNull)
	{
		this.idProfessorNull = idProfessorNull;
	}

	/** 
	 * Gets the value of idProfessorNull
	 */
	public boolean isIdProfessorNull()
	{
		return idProfessorNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ProfDiscPk)) {
			return false;
		}
		
		final ProfDiscPk _cast = (ProfDiscPk) _other;
		if (idProfessor != _cast.idProfessor) {
			return false;
		}
		
		if (idDisciplina == null ? _cast.idDisciplina != idDisciplina : !idDisciplina.equals( _cast.idDisciplina )) {
			return false;
		}
		
		if (idProfessorNull != _cast.idProfessorNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idProfessor;
		if (idDisciplina != null) {
			_hashCode = 29 * _hashCode + idDisciplina.hashCode();
		}
		
		_hashCode = 29 * _hashCode + (idProfessorNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mycompany.myapp.dto.ProfDiscPk: " );
		ret.append( "idProfessor=" + idProfessor );
		ret.append( ", idDisciplina=" + idDisciplina );
		return ret.toString();
	}

}
