/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mycompany.myapp.dto;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/** 
 * This class represents the primary key of the professor table.
 */
public class ProfessorPk implements Serializable
{
	protected int idProfessor;

	/** 
	 * This attribute represents whether the primitive attribute idProfessor is null.
	 */
	protected boolean idProfessorNull;

	/** 
	 * Sets the value of idProfessor
	 */
	public void setIdProfessor(int idProfessor)
	{
		this.idProfessor = idProfessor;
	}

	/** 
	 * Gets the value of idProfessor
	 */
	public int getIdProfessor()
	{
		return idProfessor;
	}

	/**
	 * Method 'ProfessorPk'
	 * 
	 */
	public ProfessorPk()
	{
	}

	/**
	 * Method 'ProfessorPk'
	 * 
	 * @param idProfessor
	 */
	public ProfessorPk(final int idProfessor)
	{
		this.idProfessor = idProfessor;
	}

	/** 
	 * Sets the value of idProfessorNull
	 */
	public void setIdProfessorNull(boolean idProfessorNull)
	{
		this.idProfessorNull = idProfessorNull;
	}

	/** 
	 * Gets the value of idProfessorNull
	 */
	public boolean isIdProfessorNull()
	{
		return idProfessorNull;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ProfessorPk)) {
			return false;
		}
		
		final ProfessorPk _cast = (ProfessorPk) _other;
		if (idProfessor != _cast.idProfessor) {
			return false;
		}
		
		if (idProfessorNull != _cast.idProfessorNull) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idProfessor;
		_hashCode = 29 * _hashCode + (idProfessorNull ? 1 : 0);
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mycompany.myapp.dto.ProfessorPk: " );
		ret.append( "idProfessor=" + idProfessor );
		return ret.toString();
	}

}
