/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mycompany.myapp.dto;

import com.mycompany.myapp.dao.*;
import com.mycompany.myapp.factory.*;
import com.mycompany.myapp.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class ProfDisc implements Serializable
{
	/** 
	 * This attribute maps to the column idProfessor in the prof_disc table.
	 */
	protected int idProfessor;

	/** 
	 * This attribute maps to the column idDisciplina in the prof_disc table.
	 */
	protected String idDisciplina;

	/** 
	 * This attribute maps to the column Livro in the prof_disc table.
	 */
	protected String livro;

	/**
	 * Method 'ProfDisc'
	 * 
	 */
	public ProfDisc()
	{
	}

	/**
	 * Method 'getIdProfessor'
	 * 
	 * @return int
	 */
	public int getIdProfessor()
	{
		return idProfessor;
	}

	/**
	 * Method 'setIdProfessor'
	 * 
	 * @param idProfessor
	 */
	public void setIdProfessor(int idProfessor)
	{
		this.idProfessor = idProfessor;
	}

	/**
	 * Method 'getIdDisciplina'
	 * 
	 * @return String
	 */
	public String getIdDisciplina()
	{
		return idDisciplina;
	}

	/**
	 * Method 'setIdDisciplina'
	 * 
	 * @param idDisciplina
	 */
	public void setIdDisciplina(String idDisciplina)
	{
		this.idDisciplina = idDisciplina;
	}

	/**
	 * Method 'getLivro'
	 * 
	 * @return String
	 */
	public String getLivro()
	{
		return livro;
	}

	/**
	 * Method 'setLivro'
	 * 
	 * @param livro
	 */
	public void setLivro(String livro)
	{
		this.livro = livro;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof ProfDisc)) {
			return false;
		}
		
		final ProfDisc _cast = (ProfDisc) _other;
		if (idProfessor != _cast.idProfessor) {
			return false;
		}
		
		if (idDisciplina == null ? _cast.idDisciplina != idDisciplina : !idDisciplina.equals( _cast.idDisciplina )) {
			return false;
		}
		
		if (livro == null ? _cast.livro != livro : !livro.equals( _cast.livro )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idProfessor;
		if (idDisciplina != null) {
			_hashCode = 29 * _hashCode + idDisciplina.hashCode();
		}
		
		if (livro != null) {
			_hashCode = 29 * _hashCode + livro.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return ProfDiscPk
	 */
	public ProfDiscPk createPk()
	{
		return new ProfDiscPk(idProfessor, idDisciplina);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mycompany.myapp.dto.ProfDisc: " );
		ret.append( "idProfessor=" + idProfessor );
		ret.append( ", idDisciplina=" + idDisciplina );
		ret.append( ", livro=" + livro );
		return ret.toString();
	}

}
