/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mycompany.myapp.dto;

import com.mycompany.myapp.dao.*;
import com.mycompany.myapp.factory.*;
import com.mycompany.myapp.exceptions.*;
import java.io.Serializable;
import java.util.*;

public class Turmas implements Serializable
{
	/** 
	 * This attribute maps to the column idProfessor in the turmas table.
	 */
	protected int idProfessor;

	/** 
	 * This attribute maps to the column idDisciplina in the turmas table.
	 */
	protected String idDisciplina;

	/** 
	 * This attribute maps to the column Horario in the turmas table.
	 */
	protected String horario;

	/** 
	 * This attribute maps to the column Aula in the turmas table.
	 */
	protected String aula;

	/**
	 * Method 'Turmas'
	 * 
	 */
	public Turmas()
	{
	}

	/**
	 * Method 'getIdProfessor'
	 * 
	 * @return int
	 */
	public int getIdProfessor()
	{
		return idProfessor;
	}

	/**
	 * Method 'setIdProfessor'
	 * 
	 * @param idProfessor
	 */
	public void setIdProfessor(int idProfessor)
	{
		this.idProfessor = idProfessor;
	}

	/**
	 * Method 'getIdDisciplina'
	 * 
	 * @return String
	 */
	public String getIdDisciplina()
	{
		return idDisciplina;
	}

	/**
	 * Method 'setIdDisciplina'
	 * 
	 * @param idDisciplina
	 */
	public void setIdDisciplina(String idDisciplina)
	{
		this.idDisciplina = idDisciplina;
	}

	/**
	 * Method 'getHorario'
	 * 
	 * @return String
	 */
	public String getHorario()
	{
		return horario;
	}

	/**
	 * Method 'setHorario'
	 * 
	 * @param horario
	 */
	public void setHorario(String horario)
	{
		this.horario = horario;
	}

	/**
	 * Method 'getAula'
	 * 
	 * @return String
	 */
	public String getAula()
	{
		return aula;
	}

	/**
	 * Method 'setAula'
	 * 
	 * @param aula
	 */
	public void setAula(String aula)
	{
		this.aula = aula;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof Turmas)) {
			return false;
		}
		
		final Turmas _cast = (Turmas) _other;
		if (idProfessor != _cast.idProfessor) {
			return false;
		}
		
		if (idDisciplina == null ? _cast.idDisciplina != idDisciplina : !idDisciplina.equals( _cast.idDisciplina )) {
			return false;
		}
		
		if (horario == null ? _cast.horario != horario : !horario.equals( _cast.horario )) {
			return false;
		}
		
		if (aula == null ? _cast.aula != aula : !aula.equals( _cast.aula )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + idProfessor;
		if (idDisciplina != null) {
			_hashCode = 29 * _hashCode + idDisciplina.hashCode();
		}
		
		if (horario != null) {
			_hashCode = 29 * _hashCode + horario.hashCode();
		}
		
		if (aula != null) {
			_hashCode = 29 * _hashCode + aula.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'createPk'
	 * 
	 * @return TurmasPk
	 */
	public TurmasPk createPk()
	{
		return new TurmasPk(idProfessor);
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mycompany.myapp.dto.Turmas: " );
		ret.append( "idProfessor=" + idProfessor );
		ret.append( ", idDisciplina=" + idDisciplina );
		ret.append( ", horario=" + horario );
		ret.append( ", aula=" + aula );
		return ret.toString();
	}

}
