/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mycompany.myapp.factory;

import java.sql.Connection;
import com.mycompany.myapp.dao.*;
import com.mycompany.myapp.jdbc.*;

public class DisciplinasDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return DisciplinasDao
	 */
	public static DisciplinasDao create()
	{
		return new DisciplinasDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return DisciplinasDao
	 */
	public static DisciplinasDao create(Connection conn)
	{
		return new DisciplinasDaoImpl( conn );
	}

}
