/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mycompany.myapp.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.mycompany.myapp.dao.DisciplinasDao;
import com.mycompany.myapp.dto.Disciplinas;
import com.mycompany.myapp.exceptions.DisciplinasDaoException;
import com.mycompany.myapp.factory.DisciplinasDaoFactory;

public class DisciplinasDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findWhereIdDisciplinaEquals(0);
		// findWhereDisciplinaEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			DisciplinasDao _dao = getDisciplinasDao();
			Disciplinas _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdDisciplinaEquals'
	 * 
	 * @param idDisciplina
	 */
	public static void findWhereIdDisciplinaEquals(int idDisciplina)
	{
		try {
			DisciplinasDao _dao = getDisciplinasDao();
			Disciplinas _result[] = _dao.findWhereIdDisciplinaEquals(idDisciplina);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereDisciplinaEquals'
	 * 
	 * @param disciplina
	 */
	public static void findWhereDisciplinaEquals(String disciplina)
	{
		try {
			DisciplinasDao _dao = getDisciplinasDao();
			Disciplinas _result[] = _dao.findWhereDisciplinaEquals(disciplina);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getDisciplinasDao'
	 * 
	 * @return DisciplinasDao
	 */
	public static DisciplinasDao getDisciplinasDao()
	{
		return DisciplinasDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Disciplinas dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getIdDisciplina() );
		buf.append( ", " );
		buf.append( dto.getDisciplina() );
		System.out.println( buf.toString() );
	}

}
