/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mycompany.myapp.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.mycompany.myapp.dao.DiscLivroDao;
import com.mycompany.myapp.dto.DiscLivro;
import com.mycompany.myapp.exceptions.DiscLivroDaoException;
import com.mycompany.myapp.factory.DiscLivroDaoFactory;

public class DiscLivroDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findWhereIdDisciplinaEquals(0);
		// findWhereLivroEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			DiscLivroDao _dao = getDiscLivroDao();
			DiscLivro _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdDisciplinaEquals'
	 * 
	 * @param idDisciplina
	 */
	public static void findWhereIdDisciplinaEquals(int idDisciplina)
	{
		try {
			DiscLivroDao _dao = getDiscLivroDao();
			DiscLivro _result[] = _dao.findWhereIdDisciplinaEquals(idDisciplina);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereLivroEquals'
	 * 
	 * @param livro
	 */
	public static void findWhereLivroEquals(String livro)
	{
		try {
			DiscLivroDao _dao = getDiscLivroDao();
			DiscLivro _result[] = _dao.findWhereLivroEquals(livro);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getDiscLivroDao'
	 * 
	 * @return DiscLivroDao
	 */
	public static DiscLivroDao getDiscLivroDao()
	{
		return DiscLivroDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(DiscLivro dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getIdDisciplina() );
		buf.append( ", " );
		buf.append( dto.getLivro() );
		System.out.println( buf.toString() );
	}

}
