/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mycompany.myapp.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.mycompany.myapp.dao.LivrosDao;
import com.mycompany.myapp.dto.Livros;
import com.mycompany.myapp.exceptions.LivrosDaoException;
import com.mycompany.myapp.factory.LivrosDaoFactory;

public class LivrosDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findWhereLivroEquals(0);
		// findWhereEditorialEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			LivrosDao _dao = getLivrosDao();
			Livros _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereLivroEquals'
	 * 
	 * @param livro
	 */
	public static void findWhereLivroEquals(int livro)
	{
		try {
			LivrosDao _dao = getLivrosDao();
			Livros _result[] = _dao.findWhereLivroEquals(livro);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereEditorialEquals'
	 * 
	 * @param editorial
	 */
	public static void findWhereEditorialEquals(String editorial)
	{
		try {
			LivrosDao _dao = getLivrosDao();
			Livros _result[] = _dao.findWhereEditorialEquals(editorial);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getLivrosDao'
	 * 
	 * @return LivrosDao
	 */
	public static LivrosDao getLivrosDao()
	{
		return LivrosDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Livros dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getLivro() );
		buf.append( ", " );
		buf.append( dto.getEditorial() );
		System.out.println( buf.toString() );
	}

}
