/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mycompany.myapp.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.mycompany.myapp.dao.ProfessorDao;
import com.mycompany.myapp.dto.Professor;
import com.mycompany.myapp.exceptions.ProfessorDaoException;
import com.mycompany.myapp.factory.ProfessorDaoFactory;

public class ProfessorDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		findAll();
		// findWhereIdProfessorEquals(0);
		// findWhereProfessorEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			ProfessorDao _dao = getProfessorDao();
			Professor _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdProfessorEquals'
	 * 
	 * @param idProfessor
	 */
	public static void findWhereIdProfessorEquals(int idProfessor)
	{
		try {
			ProfessorDao _dao = getProfessorDao();
			Professor _result[] = _dao.findWhereIdProfessorEquals(idProfessor);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereProfessorEquals'
	 * 
	 * @param professor
	 */
	public static void findWhereProfessorEquals(String professor)
	{
		try {
			ProfessorDao _dao = getProfessorDao();
			Professor _result[] = _dao.findWhereProfessorEquals(professor);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getProfessorDao'
	 * 
	 * @return ProfessorDao
	 */
	public static ProfessorDao getProfessorDao()
	{
		return ProfessorDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Professor dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getIdProfessor() );
		buf.append( ", " );
		buf.append( dto.getProfessor() );
		System.out.println( buf.toString() );
	}

}
