/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mycompany.myapp.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.mycompany.myapp.dao.ProfDiscDao;
import com.mycompany.myapp.dto.ProfDisc;
import com.mycompany.myapp.exceptions.ProfDiscDaoException;
import com.mycompany.myapp.factory.ProfDiscDaoFactory;

public class ProfDiscDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findWhereIdProfessorEquals(0);
		// findWhereIdDisciplinaEquals("");
		// findWhereLivroEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			ProfDiscDao _dao = getProfDiscDao();
			ProfDisc _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdProfessorEquals'
	 * 
	 * @param idProfessor
	 */
	public static void findWhereIdProfessorEquals(int idProfessor)
	{
		try {
			ProfDiscDao _dao = getProfDiscDao();
			ProfDisc _result[] = _dao.findWhereIdProfessorEquals(idProfessor);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdDisciplinaEquals'
	 * 
	 * @param idDisciplina
	 */
	public static void findWhereIdDisciplinaEquals(String idDisciplina)
	{
		try {
			ProfDiscDao _dao = getProfDiscDao();
			ProfDisc _result[] = _dao.findWhereIdDisciplinaEquals(idDisciplina);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereLivroEquals'
	 * 
	 * @param livro
	 */
	public static void findWhereLivroEquals(String livro)
	{
		try {
			ProfDiscDao _dao = getProfDiscDao();
			ProfDisc _result[] = _dao.findWhereLivroEquals(livro);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getProfDiscDao'
	 * 
	 * @return ProfDiscDao
	 */
	public static ProfDiscDao getProfDiscDao()
	{
		return ProfDiscDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(ProfDisc dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getIdProfessor() );
		buf.append( ", " );
		buf.append( dto.getIdDisciplina() );
		buf.append( ", " );
		buf.append( dto.getLivro() );
		System.out.println( buf.toString() );
	}

}
