/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mycompany.myapp.example;

import java.math.*;
import java.util.Date;
import java.util.Collection;
import com.mycompany.myapp.dao.TurmasDao;
import com.mycompany.myapp.dto.Turmas;
import com.mycompany.myapp.exceptions.TurmasDaoException;
import com.mycompany.myapp.factory.TurmasDaoFactory;

public class TurmasDaoSample
{
	/**
	 * Method 'main'
	 * 
	 * @param arg
	 * @throws Exception
	 */
	public static void main(String[] arg) throws Exception
	{
		// Uncomment one of the lines below to test the generated code
		
		// findAll();
		// findWhereIdProfessorEquals(0);
		// findWhereIdDisciplinaEquals("");
		// findWhereHorarioEquals("");
		// findWhereAulaEquals("");
	}

	/**
	 * Method 'findAll'
	 * 
	 */
	public static void findAll()
	{
		try {
			TurmasDao _dao = getTurmasDao();
			Turmas _result[] = _dao.findAll();
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdProfessorEquals'
	 * 
	 * @param idProfessor
	 */
	public static void findWhereIdProfessorEquals(int idProfessor)
	{
		try {
			TurmasDao _dao = getTurmasDao();
			Turmas _result[] = _dao.findWhereIdProfessorEquals(idProfessor);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereIdDisciplinaEquals'
	 * 
	 * @param idDisciplina
	 */
	public static void findWhereIdDisciplinaEquals(String idDisciplina)
	{
		try {
			TurmasDao _dao = getTurmasDao();
			Turmas _result[] = _dao.findWhereIdDisciplinaEquals(idDisciplina);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereHorarioEquals'
	 * 
	 * @param horario
	 */
	public static void findWhereHorarioEquals(String horario)
	{
		try {
			TurmasDao _dao = getTurmasDao();
			Turmas _result[] = _dao.findWhereHorarioEquals(horario);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'findWhereAulaEquals'
	 * 
	 * @param aula
	 */
	public static void findWhereAulaEquals(String aula)
	{
		try {
			TurmasDao _dao = getTurmasDao();
			Turmas _result[] = _dao.findWhereAulaEquals(aula);
			for (int i=0; i<_result.length; i++ ) {
				display( _result[i] );
			}
		
		}
		catch (Exception _e) {
			_e.printStackTrace();
		}
		
	}

	/**
	 * Method 'getTurmasDao'
	 * 
	 * @return TurmasDao
	 */
	public static TurmasDao getTurmasDao()
	{
		return TurmasDaoFactory.create();
	}

	/**
	 * Method 'display'
	 * 
	 * @param dto
	 */
	public static void display(Turmas dto)
	{
		StringBuffer buf = new StringBuffer();
		buf.append( dto.getIdProfessor() );
		buf.append( ", " );
		buf.append( dto.getIdDisciplina() );
		buf.append( ", " );
		buf.append( dto.getHorario() );
		buf.append( ", " );
		buf.append( dto.getAula() );
		System.out.println( buf.toString() );
	}

}
