/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mycompany.myapp.jdbc;

import com.mycompany.myapp.dao.*;
import com.mycompany.myapp.factory.*;
import com.mycompany.myapp.dto.*;
import com.mycompany.myapp.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class DisciplinasDaoImpl extends AbstractDAO implements DisciplinasDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT idDisciplina, Disciplina FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( idDisciplina, Disciplina ) VALUES ( ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET idDisciplina = ?, Disciplina = ? WHERE idDisciplina = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE idDisciplina = ?";

	/** 
	 * Index of column idDisciplina
	 */
	protected static final int COLUMN_ID_DISCIPLINA = 1;

	/** 
	 * Index of column Disciplina
	 */
	protected static final int COLUMN_DISCIPLINA = 2;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 2;

	/** 
	 * Index of primary-key column idDisciplina
	 */
	protected static final int PK_COLUMN_ID_DISCIPLINA = 1;

	/** 
	 * Inserts a new row in the disciplinas table.
	 */
	public DisciplinasPk insert(Disciplinas dto) throws DisciplinasDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT, Statement.RETURN_GENERATED_KEYS );
			int index = 1;
			stmt.setInt( index++, dto.getIdDisciplina() );
			stmt.setString( index++, dto.getDisciplina() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		
			// retrieve values from auto-increment columns
			rs = stmt.getGeneratedKeys();
			if (rs != null && rs.next()) {
				dto.setIdDisciplina( rs.getInt( 1 ) );
			}
		
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new DisciplinasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the disciplinas table.
	 */
	public void update(DisciplinasPk pk, Disciplinas dto) throws DisciplinasDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getIdDisciplina() );
			stmt.setString( index++, dto.getDisciplina() );
			stmt.setInt( 3, pk.getIdDisciplina() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new DisciplinasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the disciplinas table.
	 */
	public void delete(DisciplinasPk pk) throws DisciplinasDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getIdDisciplina() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new DisciplinasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the disciplinas table that matches the specified primary-key value.
	 */
	public Disciplinas findByPrimaryKey(DisciplinasPk pk) throws DisciplinasDaoException
	{
		return findByPrimaryKey( pk.getIdDisciplina() );
	}

	/** 
	 * Returns all rows from the disciplinas table that match the criteria 'idDisciplina = :idDisciplina'.
	 */
	public Disciplinas findByPrimaryKey(int idDisciplina) throws DisciplinasDaoException
	{
		Disciplinas ret[] = findByDynamicSelect( SQL_SELECT + " WHERE idDisciplina = ?", new Object[] {  new Integer(idDisciplina) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the disciplinas table that match the criteria ''.
	 */
	public Disciplinas[] findAll() throws DisciplinasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY idDisciplina", null );
	}

	/** 
	 * Returns all rows from the disciplinas table that match the criteria 'idDisciplina = :idDisciplina'.
	 */
	public Disciplinas[] findWhereIdDisciplinaEquals(int idDisciplina) throws DisciplinasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE idDisciplina = ? ORDER BY idDisciplina", new Object[] {  new Integer(idDisciplina) } );
	}

	/** 
	 * Returns all rows from the disciplinas table that match the criteria 'Disciplina = :disciplina'.
	 */
	public Disciplinas[] findWhereDisciplinaEquals(String disciplina) throws DisciplinasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE Disciplina = ? ORDER BY Disciplina", new Object[] { disciplina } );
	}

	/**
	 * Method 'DisciplinasDaoImpl'
	 * 
	 */
	public DisciplinasDaoImpl()
	{
	}

	/**
	 * Method 'DisciplinasDaoImpl'
	 * 
	 * @param userConn
	 */
	public DisciplinasDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "exemplo.disciplinas";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Disciplinas fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Disciplinas dto = new Disciplinas();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Disciplinas[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Disciplinas dto = new Disciplinas();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Disciplinas ret[] = new Disciplinas[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Disciplinas dto, ResultSet rs) throws SQLException
	{
		dto.setIdDisciplina( rs.getInt( COLUMN_ID_DISCIPLINA ) );
		dto.setDisciplina( rs.getString( COLUMN_DISCIPLINA ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Disciplinas dto)
	{
	}

	/** 
	 * Returns all rows from the disciplinas table that match the specified arbitrary SQL statement
	 */
	public Disciplinas[] findByDynamicSelect(String sql, Object[] sqlParams) throws DisciplinasDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new DisciplinasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the disciplinas table that match the specified arbitrary SQL statement
	 */
	public Disciplinas[] findByDynamicWhere(String sql, Object[] sqlParams) throws DisciplinasDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new DisciplinasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
