/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mycompany.myapp.jdbc;

import com.mycompany.myapp.dao.*;
import com.mycompany.myapp.factory.*;
import com.mycompany.myapp.dto.*;
import com.mycompany.myapp.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class DiscLivroDaoImpl extends AbstractDAO implements DiscLivroDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT idDisciplina, Livro FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( idDisciplina, Livro ) VALUES ( ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET idDisciplina = ?, Livro = ? WHERE idDisciplina = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE idDisciplina = ?";

	/** 
	 * Index of column idDisciplina
	 */
	protected static final int COLUMN_ID_DISCIPLINA = 1;

	/** 
	 * Index of column Livro
	 */
	protected static final int COLUMN_LIVRO = 2;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 2;

	/** 
	 * Index of primary-key column idDisciplina
	 */
	protected static final int PK_COLUMN_ID_DISCIPLINA = 1;

	/** 
	 * Inserts a new row in the disc_livro table.
	 */
	public DiscLivroPk insert(DiscLivro dto) throws DiscLivroDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setInt( index++, dto.getIdDisciplina() );
			stmt.setString( index++, dto.getLivro() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new DiscLivroDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the disc_livro table.
	 */
	public void update(DiscLivroPk pk, DiscLivro dto) throws DiscLivroDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getIdDisciplina() );
			stmt.setString( index++, dto.getLivro() );
			stmt.setInt( 3, pk.getIdDisciplina() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new DiscLivroDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the disc_livro table.
	 */
	public void delete(DiscLivroPk pk) throws DiscLivroDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getIdDisciplina() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new DiscLivroDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the disc_livro table that matches the specified primary-key value.
	 */
	public DiscLivro findByPrimaryKey(DiscLivroPk pk) throws DiscLivroDaoException
	{
		return findByPrimaryKey( pk.getIdDisciplina() );
	}

	/** 
	 * Returns all rows from the disc_livro table that match the criteria 'idDisciplina = :idDisciplina'.
	 */
	public DiscLivro findByPrimaryKey(int idDisciplina) throws DiscLivroDaoException
	{
		DiscLivro ret[] = findByDynamicSelect( SQL_SELECT + " WHERE idDisciplina = ?", new Object[] {  new Integer(idDisciplina) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the disc_livro table that match the criteria ''.
	 */
	public DiscLivro[] findAll() throws DiscLivroDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY idDisciplina", null );
	}

	/** 
	 * Returns all rows from the disc_livro table that match the criteria 'idDisciplina = :idDisciplina'.
	 */
	public DiscLivro[] findWhereIdDisciplinaEquals(int idDisciplina) throws DiscLivroDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE idDisciplina = ? ORDER BY idDisciplina", new Object[] {  new Integer(idDisciplina) } );
	}

	/** 
	 * Returns all rows from the disc_livro table that match the criteria 'Livro = :livro'.
	 */
	public DiscLivro[] findWhereLivroEquals(String livro) throws DiscLivroDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE Livro = ? ORDER BY Livro", new Object[] { livro } );
	}

	/**
	 * Method 'DiscLivroDaoImpl'
	 * 
	 */
	public DiscLivroDaoImpl()
	{
	}

	/**
	 * Method 'DiscLivroDaoImpl'
	 * 
	 * @param userConn
	 */
	public DiscLivroDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "exemplo.disc_livro";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected DiscLivro fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			DiscLivro dto = new DiscLivro();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected DiscLivro[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			DiscLivro dto = new DiscLivro();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		DiscLivro ret[] = new DiscLivro[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(DiscLivro dto, ResultSet rs) throws SQLException
	{
		dto.setIdDisciplina( rs.getInt( COLUMN_ID_DISCIPLINA ) );
		dto.setLivro( rs.getString( COLUMN_LIVRO ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(DiscLivro dto)
	{
	}

	/** 
	 * Returns all rows from the disc_livro table that match the specified arbitrary SQL statement
	 */
	public DiscLivro[] findByDynamicSelect(String sql, Object[] sqlParams) throws DiscLivroDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new DiscLivroDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the disc_livro table that match the specified arbitrary SQL statement
	 */
	public DiscLivro[] findByDynamicWhere(String sql, Object[] sqlParams) throws DiscLivroDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new DiscLivroDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
