/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.mycompany.myapp.jdbc;

import com.mycompany.myapp.dao.*;
import com.mycompany.myapp.factory.*;
import com.mycompany.myapp.dto.*;
import com.mycompany.myapp.exceptions.*;
import java.sql.Connection;
import java.util.Collection;
import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Time;
import java.util.List;
import java.util.Iterator;
import java.util.ArrayList;

public class TurmasDaoImpl extends AbstractDAO implements TurmasDao
{
	/** 
	 * The factory class for this DAO has two versions of the create() method - one that
takes no arguments and one that takes a Connection argument. If the Connection version
is chosen then the connection will be stored in this attribute and will be used by all
calls to this DAO, otherwise a new Connection will be allocated for each operation.
	 */
	protected java.sql.Connection userConn;

	/** 
	 * All finder methods in this class use this SELECT constant to build their queries
	 */
	protected final String SQL_SELECT = "SELECT idProfessor, idDisciplina, Horario, Aula FROM " + getTableName() + "";

	/** 
	 * Finder methods will pass this value to the JDBC setMaxRows method
	 */
	protected int maxRows;

	/** 
	 * SQL INSERT statement for this table
	 */
	protected final String SQL_INSERT = "INSERT INTO " + getTableName() + " ( idProfessor, idDisciplina, Horario, Aula ) VALUES ( ?, ?, ?, ? )";

	/** 
	 * SQL UPDATE statement for this table
	 */
	protected final String SQL_UPDATE = "UPDATE " + getTableName() + " SET idProfessor = ?, idDisciplina = ?, Horario = ?, Aula = ? WHERE idProfessor = ?";

	/** 
	 * SQL DELETE statement for this table
	 */
	protected final String SQL_DELETE = "DELETE FROM " + getTableName() + " WHERE idProfessor = ?";

	/** 
	 * Index of column idProfessor
	 */
	protected static final int COLUMN_ID_PROFESSOR = 1;

	/** 
	 * Index of column idDisciplina
	 */
	protected static final int COLUMN_ID_DISCIPLINA = 2;

	/** 
	 * Index of column Horario
	 */
	protected static final int COLUMN_HORARIO = 3;

	/** 
	 * Index of column Aula
	 */
	protected static final int COLUMN_AULA = 4;

	/** 
	 * Number of columns
	 */
	protected static final int NUMBER_OF_COLUMNS = 4;

	/** 
	 * Index of primary-key column idProfessor
	 */
	protected static final int PK_COLUMN_ID_PROFESSOR = 1;

	/** 
	 * Inserts a new row in the turmas table.
	 */
	public TurmasPk insert(Turmas dto) throws TurmasDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			stmt = conn.prepareStatement( SQL_INSERT );
			int index = 1;
			stmt.setInt( index++, dto.getIdProfessor() );
			stmt.setString( index++, dto.getIdDisciplina() );
			stmt.setString( index++, dto.getHorario() );
			stmt.setString( index++, dto.getAula() );
			System.out.println( "Executing " + SQL_INSERT + " with DTO: " + dto );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
			reset(dto);
			return dto.createPk();
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TurmasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Updates a single row in the turmas table.
	 */
	public void update(TurmasPk pk, Turmas dto) throws TurmasDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_UPDATE + " with DTO: " + dto );
			stmt = conn.prepareStatement( SQL_UPDATE );
			int index=1;
			stmt.setInt( index++, dto.getIdProfessor() );
			stmt.setString( index++, dto.getIdDisciplina() );
			stmt.setString( index++, dto.getHorario() );
			stmt.setString( index++, dto.getAula() );
			stmt.setInt( 5, pk.getIdProfessor() );
			int rows = stmt.executeUpdate();
			reset(dto);
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TurmasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Deletes a single row in the turmas table.
	 */
	public void delete(TurmasPk pk) throws TurmasDaoException
	{
		long t1 = System.currentTimeMillis();
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			System.out.println( "Executing " + SQL_DELETE + " with PK: " + pk );
			stmt = conn.prepareStatement( SQL_DELETE );
			stmt.setInt( 1, pk.getIdProfessor() );
			int rows = stmt.executeUpdate();
			long t2 = System.currentTimeMillis();
			System.out.println( rows + " rows affected (" + (t2-t1) + " ms)" );
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TurmasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns the rows from the turmas table that matches the specified primary-key value.
	 */
	public Turmas findByPrimaryKey(TurmasPk pk) throws TurmasDaoException
	{
		return findByPrimaryKey( pk.getIdProfessor() );
	}

	/** 
	 * Returns all rows from the turmas table that match the criteria 'idProfessor = :idProfessor'.
	 */
	public Turmas findByPrimaryKey(int idProfessor) throws TurmasDaoException
	{
		Turmas ret[] = findByDynamicSelect( SQL_SELECT + " WHERE idProfessor = ?", new Object[] {  new Integer(idProfessor) } );
		return ret.length==0 ? null : ret[0];
	}

	/** 
	 * Returns all rows from the turmas table that match the criteria ''.
	 */
	public Turmas[] findAll() throws TurmasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " ORDER BY idProfessor", null );
	}

	/** 
	 * Returns all rows from the turmas table that match the criteria 'idProfessor = :idProfessor'.
	 */
	public Turmas[] findWhereIdProfessorEquals(int idProfessor) throws TurmasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE idProfessor = ? ORDER BY idProfessor", new Object[] {  new Integer(idProfessor) } );
	}

	/** 
	 * Returns all rows from the turmas table that match the criteria 'idDisciplina = :idDisciplina'.
	 */
	public Turmas[] findWhereIdDisciplinaEquals(String idDisciplina) throws TurmasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE idDisciplina = ? ORDER BY idDisciplina", new Object[] { idDisciplina } );
	}

	/** 
	 * Returns all rows from the turmas table that match the criteria 'Horario = :horario'.
	 */
	public Turmas[] findWhereHorarioEquals(String horario) throws TurmasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE Horario = ? ORDER BY Horario", new Object[] { horario } );
	}

	/** 
	 * Returns all rows from the turmas table that match the criteria 'Aula = :aula'.
	 */
	public Turmas[] findWhereAulaEquals(String aula) throws TurmasDaoException
	{
		return findByDynamicSelect( SQL_SELECT + " WHERE Aula = ? ORDER BY Aula", new Object[] { aula } );
	}

	/**
	 * Method 'TurmasDaoImpl'
	 * 
	 */
	public TurmasDaoImpl()
	{
	}

	/**
	 * Method 'TurmasDaoImpl'
	 * 
	 * @param userConn
	 */
	public TurmasDaoImpl(final java.sql.Connection userConn)
	{
		this.userConn = userConn;
	}

	/** 
	 * Sets the value of maxRows
	 */
	public void setMaxRows(int maxRows)
	{
		this.maxRows = maxRows;
	}

	/** 
	 * Gets the value of maxRows
	 */
	public int getMaxRows()
	{
		return maxRows;
	}

	/**
	 * Method 'getTableName'
	 * 
	 * @return String
	 */
	public String getTableName()
	{
		return "exemplo.turmas";
	}

	/** 
	 * Fetches a single row from the result set
	 */
	protected Turmas fetchSingleResult(ResultSet rs) throws SQLException
	{
		if (rs.next()) {
			Turmas dto = new Turmas();
			populateDto( dto, rs);
			return dto;
		} else {
			return null;
		}
		
	}

	/** 
	 * Fetches multiple rows from the result set
	 */
	protected Turmas[] fetchMultiResults(ResultSet rs) throws SQLException
	{
		Collection resultList = new ArrayList();
		while (rs.next()) {
			Turmas dto = new Turmas();
			populateDto( dto, rs);
			resultList.add( dto );
		}
		
		Turmas ret[] = new Turmas[ resultList.size() ];
		resultList.toArray( ret );
		return ret;
	}

	/** 
	 * Populates a DTO with data from a ResultSet
	 */
	protected void populateDto(Turmas dto, ResultSet rs) throws SQLException
	{
		dto.setIdProfessor( rs.getInt( COLUMN_ID_PROFESSOR ) );
		dto.setIdDisciplina( rs.getString( COLUMN_ID_DISCIPLINA ) );
		dto.setHorario( rs.getString( COLUMN_HORARIO ) );
		dto.setAula( rs.getString( COLUMN_AULA ) );
	}

	/** 
	 * Resets the modified attributes in the DTO
	 */
	protected void reset(Turmas dto)
	{
	}

	/** 
	 * Returns all rows from the turmas table that match the specified arbitrary SQL statement
	 */
	public Turmas[] findByDynamicSelect(String sql, Object[] sqlParams) throws TurmasDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TurmasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

	/** 
	 * Returns all rows from the turmas table that match the specified arbitrary SQL statement
	 */
	public Turmas[] findByDynamicWhere(String sql, Object[] sqlParams) throws TurmasDaoException
	{
		// declare variables
		final boolean isConnSupplied = (userConn != null);
		Connection conn = null;
		PreparedStatement stmt = null;
		ResultSet rs = null;
		
		try {
			// get the user-specified connection or get a connection from the ResourceManager
			conn = isConnSupplied ? userConn : ResourceManager.getConnection();
		
			// construct the SQL statement
			final String SQL = SQL_SELECT + " WHERE " + sql;
		
		
			System.out.println( "Executing " + SQL );
			// prepare statement
			stmt = conn.prepareStatement( SQL );
			stmt.setMaxRows( maxRows );
		
			// bind parameters
			for (int i=0; sqlParams!=null && i<sqlParams.length; i++ ) {
				stmt.setObject( i+1, sqlParams[i] );
			}
		
		
			rs = stmt.executeQuery();
		
			// fetch the results
			return fetchMultiResults(rs);
		}
		catch (Exception _e) {
			_e.printStackTrace();
			throw new TurmasDaoException( "Exception: " + _e.getMessage(), _e );
		}
		finally {
			ResourceManager.close(rs);
			ResourceManager.close(stmt);
			if (!isConnSupplied) {
				ResourceManager.close(conn);
			}
		
		}
		
	}

}
